on: 
  workflow_dispatch:
jobs:
  hybrid_job:
    
    runs-on: ubuntu-latest
    steps:
      - name: Run command in ubuntu VM
        run: echo "This runs on the ubuntu VM"

      - name: Run command in alpine container
        uses: docker://alpine:3.14
        with: 
          entrypoint: /bin/sh
          args: |
            - -c echo "This runs inside an Alpine container"

      - name: Run another command in ubuntu VM
        run: echo "This also runs on the ubuntu VM"
  dockerized_job:
    runs-on: ununtu-latest
    container:
      image: node:20
    steps:
      - run: node --version
      - run: echo "Thsi runs inside a nodejs container"

  dockerized_job1:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io.my-org/my-private-image:latest
      credentials:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - run: node --version
      - run: echo "Thsi runs inside a nodejs container"



