on: 
  workflow_dispatch:
jobs:
  examble:
    runs-on: ubuntu-latest
    steps:
      - name: check file exists
        run: |
          if [[ -f "config.yml" ]]; then
            echo "::debug:: config.yml exists"
          else
            echo "::error:: config.yml doesn't exist"
          fi
       
