on: 
  workflow_dispatch:
jobs:
  examble:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          depricated=true
          if [[ depricated ]]; then
            echo "::warning:: depricated function found"
          fi
