on:
  workflow_dispatch:


jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [23.x, 24.x, 25.x]
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@6.2.0
        with: 
          node-version: ${{ matrix.node_version }}
