on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [14.x,15.x,16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.version}}
      - name: Print OS
        run: echo "Running on ${{ runner.os }}"

      - name: Done
        run: echo "Job completed successfully"
